### ISSUE TITLE
upfirdn2d_plugin error

### ISSUE THREAD

**Issue by Kaitlin-Wang** [mahdi-darvish/GAN-augmented-pet-classifier#1]
Hello,
I encountered the following error while training on your cropped dataset:
I checked the StyleGAN2 repo and couldn't find a similar issue.
Any suggestions?

`raining duration: 25000 kimg
Number of GPUs: 1
Number of images: 48255
Image resolution: 128
Conditional model: False
Dataset x-flips: False

Creating output directory...
Launching processes...
Loading training set...

Num images: 48255
Image shape: [3, 128, 128]
Label shape: [0]

Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
C:\Users\Graham\Desktop\ICSCapstone\stylegan2-ada-pytorch-main\torch_utils\ops\bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
env=env)
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 468, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):Traceback (most recent call last):
File "C:\Users\Graham\Desktop\ICSCapstone\stylegan2-ada-pytorch-main\torch_utils\ops\upfirdn2d.py", line 32, in _init
_plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
File "C:\Users\Graham\Desktop\ICSCapstone\stylegan2-ada-pytorch-main\torch_utils\custom_ops.py", line 110, in get_plugin
torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
keep_intermediates=keep_intermediates)
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1317, in _jit_compile
return _import_module_from_library(name, build_directory, is_python_module)
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1699, in _import_module_from_library
file, path, description = imp.find_module(module_name, [path])
File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\imp.py", line 297, in find_module
raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'upfirdn2d_plugin'`

**Comment by mahdi-darvish** [comment]
Hello Kaitlin, thanks for reaching out.

This sort of problem usually comes from multiple runs in the same environment. The 'upfirdn2d' plugin generates a 16 character key at the beginning of the run. The code tries to generate a new key and fails by stopping the current run and re-running it.

If you are using a Linux-based operating system try using this command:

`!rm -rf /root/.cache/torch_extensions/*`

It deletes the existing plugins and lets you start the training over again; if your using Windows, the path depends on your environment. It's pretty straight forward just find where Torch is installed and find the mentioned path.

I hope this helps,
Happy coding.

**Comment by Kaitlin-Wang** [comment]
Thanks for replying. That was the issue; clearing the suggested path solved the problem. 
Cheers,
